name: 'Repository Mirror Archive'
description: 'Clones repository with --mirror, creates tar archive and compresses with zstd'
author: 'Your Name'
branding:
  icon: 'archive'
  color: 'blue'

runs:
  using: 'docker'
  image: 'Dockerfile'

env:
  GITHUB_TOKEN: ${{ inputs.github-token }}